USE QLPHONGKHAMNHAKHOA

-- Tạo Login --
CREATE LOGIN ADMINISTRATOR WITH PASSWORD = 'ADMINISTRATOR'
CREATE LOGIN NHANVIEN WITH PASSWORD = 'NHANVIEN'
CREATE LOGIN NHASI WITH PASSWORD = 'NHASI'
CREATE LOGIN KHACHHANG WITH PASSWORD = 'KHACHHANG'

-- Tạo user tương ứng --
Create User ADMINISTRATOR For Login ADMINISTRATOR 
Create User NHANVIEN For Login NHANVIEN
Create User NHASI For Login NHASI
Create User KHACHHANG For Login KHACHHANG

--Phân quyền cho USER KHACHHANG--
--Khách hàng có quyền xem thông tin đăng nhập của mình trong hệ thống--
GRANT SELECT ON KHACHHANG TO KHACHHANG;
GRANT SELECT ON TAIKHOAN TO KHACHHANG;

--Khách hàng có quyền đặt lịch hẹn, xem lịch hẹn, sửa thông tin lịch hẹn --
GRANT INSERT ON CUOCHEN TO KHACHHANG;
GRANT SELECT (SDT_KH, SDT_NS, NGAY,GIO) ON CUOCHEN TO KHACHHANG;
GRANT UPDATE (SDT_KH, SDT_NS, NGAY,GIO) ON CUOCHEN TO KHACHHANG;


--Phân quyền cho USER NHASI--
--Nha sĩ có quyền thêm hồ sơ bệnh nhân (HOSOKHACHHANG) và ghi nhận thông tin về dịch vụ sử dụng và ngày khám--
GRANT INSERT ON HOSOKHACHHANG TO NHASI;
GRANT SELECT ON HOSOKHACHHANG TO NHASI;
GRANT UPDATE (ID_DICHVU) ON HOSOKHACHHANG TO NHASI;

GRANT SELECT ON DICHVU TO NHASI;

--Nha sĩ có quyền thực hiện kê đơn thuốc--
GRANT INSERT ON KEDON TO NHASI;
GRANT SELECT ON KEDON TO NHASI;
GRANT UPDATE (ID_THUOC,SOLUONG) ON KEDON TO NHASI;

GRANT SELECT ON THUOC TO NHASI;

--Phân quyền cho USER NHANVIEN--
GRANT INSERT ON CUOCHEN TO NHANVIEN;
GRANT SELECT (SDT_KH, SDT_NS, NGAY,GIO) ON CUOCHEN TO NHANVIEN;
GRANT UPDATE (SDT_KH, SDT_NS, NGAY,GIO) ON CUOCHEN TO NHANVIEN;

GRANT INSERT ON HOSOKHACHHANG TO NHANVIEN;
GRANT SELECT ON HOSOKHACHHANG TO NHANVIEN;

GRANT SELECT ON KEDON TO NHANVIEN;

GRANT SELECT ON THUOC TO NHANVIEN;
--Phân quyền cho USER ADMINISTRATOR--

ALTER ROLE [db_datawriter] ADD MEMBER ADMINISTRATOR
ALTER ROLE [db_datareader] ADD MEMBER ADMINISTRATOR
ALTER ROLE [db_securityadmin] ADD MEMBER ADMINISTRATOR